version: "3.6"
services:
  registry:
    image: verdaccio/verdaccio
    ports:
      - "4873:4873"

  publish:
    build:
      context: ../..
      dockerfile: sample-app/.local-repo/publish.dockerfile
    environment:
      - NPM_USER=admin
      - NPM_PASS=admin
      - NPM_EMAIL=admin@leancode.pl
      - NPM_REGISTRY=http://registry:4873
      - NPM_SCOPE=leancode
