image: node:12.16.0

pipelines:
  default:
    - step:
        name: Restore & test
        caches:
          - node
        script:
          - npm install
          - npx lerna bootstrap --no-ci --ignore-scripts
          - npm test
