image: node:14.17.1

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - yarn install --frozen-lockfile
          - yarn test
          - yarn lerna run build
        caches:
          - node

  tags:
    v*:
      - step:
          name: Build and test
          script:
            - yarn install --frozen-lockfile
            - yarn test
            - yarn lerna run build
          artifacts:
            - packages/*/lib/**
            - packages/Linters/*/lib/**
            - packages/Build/*/lib/**
          caches:
            - node
      - step:
          name: Publish
          trigger: manual
          deployment: production
          script:
            - npm config set //f.feedz.io/leancode/corelibrary/npm/:_authToken ${NPM_TOKEN}
            - yarn install --frozen-lockfile
            - yarn lerna publish from-git --yes
          caches:
            - node
