/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerificationImport } from './routes/verification'
import { Route as RegistrationImport } from './routes/registration'
import { Route as LoginImport } from './routes/login'

// Create/Update Routes

const VerificationRoute = VerificationImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationRoute = RegistrationImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationImport
      parentRoute: typeof rootRoute
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verification': typeof VerificationRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verification': typeof VerificationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verification': typeof VerificationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/registration' | '/verification'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/registration' | '/verification'
  id: '__root__' | '/login' | '/registration' | '/verification'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
  VerificationRoute: typeof VerificationRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
  VerificationRoute: VerificationRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/registration",
        "/verification"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/registration": {
      "filePath": "registration.tsx"
    },
    "/verification": {
      "filePath": "verification.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
